/*
* @brief Contains board specific variables and initialization functions
*/

#include <board.h>

#include <zfoc_main.h>
#include <low_level.h>

#include <Drivers/STM32/stm32_timer.hpp>

#include <adc.h>
#include <tim.h>
#include <cordic.h>
#include <crc.h>
#include <dma.h>
#include <main.h>
#include <freertos_vars.h>

// this should technically be in task_timer.cpp but let's not make a one-line file
bool TaskTimer::enabled = false;

extern "C" void SystemClock_Config(void); // defined in main.c generated by CubeMX

uint32_t adc_vals[ADC_CHANNEL_COUNT] = {1, 1, 1, 1};

#define ControlLoop_IRQHandler USB_HP_IRQHandler
#define ControlLoop_IRQn USB_HP_IRQn

Stm32SpiArbiter spi1_arbiter{&hspi1};
Stm32SpiArbiter& ext_spi_arbiter = spi1_arbiter;

// 红外传感器
uint16_t infra_adc_raw = 0;      // 红外 ADC 原始值 (12-bit, 0-4095)

Motor motors[AXIS_COUNT] = {
    {
        &htim1,
        0b111, // current_sensor_mask, all three phases
        1.0f / SHUNT_RESISTANCE, // shunt conductance [S]
    },
    {
        &htim8,
        0b111, // current_sensor_mask, all three phases
        1.0f / SHUNT_RESISTANCE, // shunt conductance [S]
    }
};

Encoder encoders[AXIS_COUNT] = {
    {
        &spi1_arbiter,
        {GPIOA, GPIO_PIN_3}, // ncs_gpio
        Encoder::MODE_SPI_ABS_AS5047P
    },
    {
        &spi1_arbiter,
        {GPIOA, GPIO_PIN_4}, // ncs_gpio
        Encoder::MODE_DISABLED
    }
};

Controller controllers[AXIS_COUNT];
TrapezoidalTrajectory traps[AXIS_COUNT];

std::array<Axis, AXIS_COUNT> axes = {
    {
        {
            5, // axis_num
            (osPriority)(osPriorityHigh + (osPriority)1), // thread_priority
            encoders[0],
            controllers[0],
            motors[0],
            traps[0]
        },
        {
            1, // axis_num
            (osPriority)(osPriorityHigh + (osPriority)1), // thread_priority
            encoders[1],
            controllers[1],
            motors[1],
            traps[1]
        }
    }
};

// TODO: Baord version check is missing due to lack of otp area

void system_init() {
    // Reset of all peripherals, Initializes the Flash interface and the Systick.
    HAL_Init();

    // Configure the system clock
    SystemClock_Config();
}

bool board_init() {
    // Disable default dual bank
    // HAL_FLASH_OB_Unlock();
    // HAL_FLASHEx_OB_DBankConfig(OB_DBANK_128_BITS);

    // Initialize all configured peripherals
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_CORDIC_Init();
    // MX_CRC_Init(); // CRC is implemented in crc.hpp with flexible init value
    // MX_FDCAN2_Init();
    // MX_FDCAN3_Init(); // FDCAN inits are done in ZfocCAN
    MX_TIM8_Init();
    MX_ADC1_Init();
    MX_ADC2_Init();
    MX_ADC3_Init();
    MX_TIM1_Init();
    MX_TIM2_Init();
    MX_TIM16_Init();
    MX_SPI1_Init();
    
    HAL_NVIC_SetPriority(ControlLoop_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(ControlLoop_IRQn);

    HAL_NVIC_SetPriority(TIM8_UP_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(TIM8_UP_IRQn);

    return true;
}

void start_timers() {
    CRITICAL_SECTION() {
        // Temporarily disable ADC triggers so they don't trigger as a side
        // effect of starting the timers.
        hadc1.Instance->JSQR &= ~ADC_JSQR_JEXTEN;
        hadc2.Instance->CFGR &= ~ADC_CFGR_EXTEN;
        hadc2.Instance->JSQR &= ~ADC_JSQR_JEXTEN;
        hadc3.Instance->CFGR &= ~ADC_CFGR_EXTEN;
        hadc3.Instance->JSQR &= ~ADC_JSQR_JEXTEN;

        /*
        * Synchronize TIM1, TIM8 and TIM13 such that:
        *  1. The triangle waveform of TIM1 leads the triangle waveform of TIM8 by a
        *     90° phase shift.
        *  2. Each TIM13 reload coincides with a TIM1 lower update event.
        */
        Stm32Timer::start_synchronously<3>(
            {&htim1, &htim8, &htim16},
            {TIM1_INIT_COUNT, 0, TIM1_INIT_COUNT /* TIM16 is on a clock as fast as TIM1 */}
        );

        hadc1.Instance->JSQR |= ADC_EXTERNALTRIGINJECCONV_EDGE_RISING;
        hadc2.Instance->CFGR |= ADC_EXTERNALTRIGCONVEDGE_RISING;
        hadc2.Instance->JSQR |= ADC_EXTERNALTRIGINJECCONV_EDGE_RISING;
        hadc3.Instance->CFGR |= ADC_EXTERNALTRIGCONVEDGE_RISING;
        hadc3.Instance->JSQR |= ADC_EXTERNALTRIGINJECCONV_EDGE_RISING;

        __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_JEOC);
        __HAL_ADC_CLEAR_FLAG(&hadc2, ADC_FLAG_JEOC);
        __HAL_ADC_CLEAR_FLAG(&hadc3, ADC_FLAG_JEOC);
        __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_EOC);
        __HAL_ADC_CLEAR_FLAG(&hadc2, ADC_FLAG_EOC);
        __HAL_ADC_CLEAR_FLAG(&hadc3, ADC_FLAG_EOC);
        __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_OVR);
        __HAL_ADC_CLEAR_FLAG(&hadc2, ADC_FLAG_OVR);
        __HAL_ADC_CLEAR_FLAG(&hadc3, ADC_FLAG_OVR);
        
        __HAL_TIM_CLEAR_IT(&htim8, TIM_IT_UPDATE);
        __HAL_TIM_ENABLE_IT(&htim8, TIM_IT_UPDATE);
    }
}

void infra_sense_adc_cb(uint32_t adc_value) {
    infra_adc_raw = (uint16_t)(adc_value & 0xFFFU);
}

static bool fetch_and_reset_adcs(
        std::optional<Iph_ABC_t>* current0,
        std::optional<Iph_ABC_t>* current1) {
    bool all_adcs_done = (ADC1->ISR & (ADC_ISR_EOC | ADC_ISR_JEOC)) == (ADC_ISR_EOC | ADC_ISR_JEOC)
        && (ADC2->ISR & (ADC_ISR_EOC | ADC_ISR_JEOC)) == (ADC_ISR_EOC | ADC_ISR_JEOC)
        && (ADC3->ISR & (ADC_ISR_EOC | ADC_ISR_JEOC)) == (ADC_ISR_EOC | ADC_ISR_JEOC);
    if (!all_adcs_done) {
        return false;
    }

    vbus_sense_adc_cb(ADC1->JDR1);
    infra_sense_adc_cb(ADC1->DR);

    std::optional<float> phA = motors[0].phase_current_from_adcval(ADC2->JDR1);
    std::optional<float> phB = motors[0].phase_current_from_adcval(ADC3->JDR1);
    if (phA.has_value() && phB.has_value()) {
        *current0 = {*phA, *phB, -*phA - *phB};
    }

    phA = motors[1].phase_current_from_adcval(ADC2->DR);
    phB = motors[1].phase_current_from_adcval(ADC3->DR);
    if (phA.has_value() && phB.has_value()) {
        *current1 = {*phA, *phB, -*phA - *phB};
    }
    
    ADC1->ISR = ~(ADC_ISR_EOC | ADC_ISR_JEOC | ADC_ISR_OVR);
    ADC2->ISR = ~(ADC_ISR_EOC | ADC_ISR_JEOC | ADC_ISR_OVR);
    ADC3->ISR = ~(ADC_ISR_EOC | ADC_ISR_JEOC | ADC_ISR_OVR);

    return true;
}

extern "C" {
void HAL_SPI_TxCpltCallback(SPI_HandleTypeDef *hspi) {
    HAL_SPI_TxRxCpltCallback(hspi);
}

void HAL_SPI_RxCpltCallback(SPI_HandleTypeDef *hspi) {
    HAL_SPI_TxRxCpltCallback(hspi);
}

void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef *hspi) {
    if (hspi == &hspi1) {
        spi1_arbiter.on_complete();
    }
}

volatile uint32_t timestamp_ = 0;
volatile bool counting_down_ = false;

void TIM8_UP_IRQHandler(void) {
    // HAL_TIM_IRQHandler(&htim8);
    COUNT_IRQ(TIM8_UP_IRQn);
    
    // Entry into this function happens at 21-23 clock cycles after the timer
    // update event.
    // __HAL_TIM_CLEAR_IT(&htim8, TIM_IT_UPDATE);
    __HAL_TIM_CLEAR_FLAG(&htim8, TIM_FLAG_UPDATE);

    // If the corresponding timer is counting up, we just sampled in SVM vector 0, i.e. real current
    // If we are counting down, we just sampled in SVM vector 7, with zero current
    bool counting_down = TIM8->CR1 & TIM_CR1_DIR;

    bool timer_update_missed = (counting_down_ == counting_down);
    if (timer_update_missed) {
        motors[0].disarm_with_error(Motor::ERROR_TIMER_UPDATE_MISSED);
        motors[1].disarm_with_error(Motor::ERROR_TIMER_UPDATE_MISSED);
        return;
    }
    counting_down_ = counting_down;

    timestamp_ += TIM_1_8_PERIOD_CLOCKS * (TIM_1_8_RCR + 1);

    if (!counting_down) {
        TaskTimer::enabled = zfoc.task_timers_armed_;
        // Run sampling handlers and kick off control tasks when TIM8 is
        // counting up.
        zfoc.sampling_cb();
        NVIC->STIR = ControlLoop_IRQn;
    } else {
        // Tentatively reset all PWM outputs to 50% duty cycles. If the control
        // loop handler finishes in time then these values will be overridden
        // before they go into effect.
        TIM1->CCR1 =
        TIM1->CCR2 =
        TIM1->CCR3 =
        TIM8->CCR1 =
        TIM8->CCR2 =
        TIM8->CCR3 =
            TIM_1_8_PERIOD_CLOCKS / 2;
    }
}

void ControlLoop_IRQHandler(void) {
    COUNT_IRQ(ControlLoop_IRQn);
    uint32_t timestamp = timestamp_;

    // Ensure that all the ADCs are done
    std::optional<Iph_ABC_t> current0;
    std::optional<Iph_ABC_t> current1;

    if (!fetch_and_reset_adcs(&current0, &current1)) {
        motors[0].disarm_with_error(Motor::ERROR_BAD_TIMING);
        motors[1].disarm_with_error(Motor::ERROR_BAD_TIMING);
    }

    // If the motor FETs are not switching then we can't measure the current
    // because for this we need the low side FET to conduct.
    // So for now we guess the current to be 0 (this is not correct shortly after
    // disarming and when the motor spins fast in idle). Passing an invalid
    // current reading would create problems with starting FOC.
    if (!(TIM1->BDTR & TIM_BDTR_MOE_Msk)) {
        current0 = {0.0f, 0.0f};
    }
    if (!(TIM8->BDTR & TIM_BDTR_MOE_Msk)) {
        current1 = {0.0f, 0.0f};
    }

    motors[0].current_meas_cb(timestamp - TIM1_INIT_COUNT, current0);
    motors[1].current_meas_cb(timestamp, current1);

    zfoc.control_loop_cb(timestamp);

    // By this time the ADCs for both M0 and M1 should have fired again. But
    // let's wait for them just to be sure.
    MEASURE_TIME(zfoc.task_times_.dc_calib_wait) {
        while (!(ADC2->ISR & ADC_ISR_EOC));
        while (!counting_down_);
    }

    if (!fetch_and_reset_adcs(&current0, &current1)) {
        motors[0].disarm_with_error(Motor::ERROR_BAD_TIMING);
        motors[1].disarm_with_error(Motor::ERROR_BAD_TIMING);
    }

    motors[0].dc_calib_cb(timestamp + TIM_1_8_PERIOD_CLOCKS * (TIM_1_8_RCR + 1) - TIM1_INIT_COUNT, current0);
    motors[1].dc_calib_cb(timestamp + TIM_1_8_PERIOD_CLOCKS * (TIM_1_8_RCR + 1), current1);

    motors[0].pwm_update_cb(timestamp + 3 * TIM_1_8_PERIOD_CLOCKS * (TIM_1_8_RCR + 1) - TIM1_INIT_COUNT);
    motors[1].pwm_update_cb(timestamp + 3 * TIM_1_8_PERIOD_CLOCKS * (TIM_1_8_RCR + 1));

    // If we did everything right, the TIM8 update handler should have been
    // called exactly once between the start of this function and now.

    if (timestamp_ != timestamp + TIM_1_8_PERIOD_CLOCKS * (TIM_1_8_RCR + 1)) {
        motors[0].disarm_with_error(Motor::ERROR_CONTROL_DEADLINE_MISSED);
        motors[1].disarm_with_error(Motor::ERROR_CONTROL_DEADLINE_MISSED);
    }

    zfoc.task_timers_armed_ = zfoc.task_timers_armed_ && !TaskTimer::enabled;
    TaskTimer::enabled = false;
}

} // extern "C"

