/*
* @brief Contains board specific variables and initialization functions
*/

#include <board.h>

#include <zfoc_main.h>
#include <low_level.h>

#include <adc.h>
#include <hrtim.h>
#include <tim.h>
#include <dma.h>
#include <usart.h>
#include <cordic.h>
#include <crc.h>
#include <main.h>
#include <freertos_vars.h>

// this should technically be in task_timer.cpp but let's not make a one-line file
bool TaskTimer::enabled = false;

extern "C" void SystemClock_Config(void); // defined in main.c generated by CubeMX

uint32_t adc_vals[ADC_CHANNEL_COUNT] = {1, 1, 1, 1};

#define ControlLoop_IRQHandler SPI1_IRQHandler
#define ControlLoop_IRQn SPI1_IRQn

Stm32Uart uart2(&huart2);

Motor motors[AXIS_COUNT] = {
    {
        &hhrtim1,
        0b111, // current_sensor_mask, all three phases
        1.0f / SHUNT_RESISTANCE, // shunt conductance [S]
    }
};

Encoder encoders[AXIS_COUNT] = {
    {
        &htim8,
        {GPIOA, GPIO_PIN_15}, // hallA
        {GPIOB, GPIO_PIN_8}, // hallB
        {GPIOB, GPIO_PIN_9}, // hallC
        &uart2
    }
};

Controller controllers[AXIS_COUNT];
TrapezoidalTrajectory traps[AXIS_COUNT];

std::array<Axis, AXIS_COUNT> axes = {
    {
        {
            0, // axis_num
            (osPriority)(osPriorityHigh + (osPriority)1), // thread_priority
            encoders[0],
            controllers[0],
            motors[0],
            traps[0]
        }
    }
};

Stm32Gpio gpios[] = {
    {GPIOA, GPIO_PIN_1}, // USART2_DE
    {GPIOA, GPIO_PIN_2}, // USART2_TX
    {GPIOA, GPIO_PIN_3}, // USART2_RX
    {GPIOA, GPIO_PIN_15}, // ENC0_HALLA
    {GPIOB, GPIO_PIN_3}, // CANB_RX
    {GPIOB, GPIO_PIN_4}, // CANB_TX
    {GPIOB, GPIO_PIN_5}, // CANA_RX
    {GPIOB, GPIO_PIN_6}, // CANA_TX
    {GPIOB, GPIO_PIN_8}, // ENC0_HALLB
    {GPIOB, GPIO_PIN_9}, // ENC0_HALLC
};


// TODO: Baord version check is missing due to lack of otp area

void system_init() {
    // Reset of all peripherals, Initializes the Flash interface and the Systick.
    HAL_Init();

    // Configure the system clock
    SystemClock_Config();
}

bool board_init() {
    // Disable default dual bank
    // HAL_FLASH_OB_Unlock();
    // HAL_FLASHEx_OB_DBankConfig(OB_DBANK_128_BITS);

    // Enable voltage reference buffer
    HAL_SYSCFG_VREFBUF_VoltageScalingConfig(SYSCFG_VREFBUF_VOLTAGE_SCALE2);
    HAL_SYSCFG_VREFBUF_HighImpedanceConfig(SYSCFG_VREFBUF_HIGH_IMPEDANCE_DISABLE);
    HAL_SYSCFG_EnableVREFBUF();

    // Initialize all configured peripherals
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_CORDIC_Init();
    // MX_CRC_Init(); // CRC is implemented in crc.hpp with flexible init value
    // MX_FDCAN2_Init();
    // MX_FDCAN3_Init(); // FDCAN inits are done in ZfocCAN
    MX_HRTIM1_Init();
    MX_TIM8_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();
    MX_ADC2_Init();
    MX_ADC3_Init();
    MX_ADC4_Init();
    MX_TIM1_Init();

    HAL_ADC_Start(&hadc1);
    HAL_ADC_Start(&hadc2);
    HAL_ADC_Start(&hadc3);
    HAL_ADC_Start(&hadc4);
    
    HAL_NVIC_SetPriority(ControlLoop_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(ControlLoop_IRQn);

    HAL_NVIC_SetPriority(HRTIM1_TIMD_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(HRTIM1_TIMD_IRQn);

    if (zfoc.config_.enable_can_a) {
        // The CAN initialization will (and must) init its own GPIOs before the
        // GPIO modes are initialized. Therefore we ensure that the later GPIO
        // mode initialization won't override the CAN mode.
        if (zfoc.config_.gpio_modes[6] != ZfocIntf::GPIO_MODE_CAN_A || zfoc.config_.gpio_modes[7] != ZfocIntf::GPIO_MODE_CAN_A) {
            zfoc.misconfigured_ = true;
        }
    }
    if (zfoc.config_.enable_can_b) {
        // The CAN initialization will (and must) init its own GPIOs before the
        // GPIO modes are initialized. Therefore we ensure that the later GPIO
        // mode initialization won't override the CAN mode.
        if (zfoc.config_.gpio_modes[4] != ZfocIntf::GPIO_MODE_CAN_B || zfoc.config_.gpio_modes[5] != ZfocIntf::GPIO_MODE_CAN_B) {
            zfoc.misconfigured_ = true;
        }
    }

    // Ensure that debug halting of the core doesn't leave the motor PWM running
    __HAL_DBGMCU_FREEZE_HRTIM1();

    return true;
}

void start_timers() {
    CRITICAL_SECTION() {
        // Temporarily disable ADC triggers so they don't trigger as a side
        // effect of starting the timers.
        hadc1.Instance->CR &= ADC_CR_ADDIS;

        // HRTIM Master timer and timer A~C are set to start in sync on the
        // first TRGO from TIM1 enable event.
        // __HAL_TIM_ENABLE(&htim1);
        HAL_HRTIM_WaveformCounterStart_IT(&hhrtim1, HRTIM_TIMERID_MASTER | HRTIM_TIMERID_TIMER_A 
            | HRTIM_TIMERID_TIMER_B | HRTIM_TIMERID_TIMER_C | HRTIM_TIMERID_TIMER_D);
        HAL_HRTIM_WaveformOutputStart(&hhrtim1, HRTIM_OUTPUT_TA1 | HRTIM_OUTPUT_TA2 | HRTIM_OUTPUT_TB1 
            | HRTIM_OUTPUT_TB2 | HRTIM_OUTPUT_TC1 | HRTIM_OUTPUT_TC2);
        HAL_TIM_Base_Start(&htim1);

        hadc1.Instance->CR &= ADC_CR_ADEN;
        
        __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_EOC);
        __HAL_ADC_CLEAR_FLAG(&hadc1, ADC_FLAG_OVR);

        // __HAL_HRTIM_TIMER_CLEAR_IT(&hhrtim1, HRTIM_TIMERINDEX_TIMER_A, HRTIM_TIM_IT_REP);
        // __HAL_HRTIM_TIMER_ENABLE_IT(&hhrtim1, HRTIM_TIMERINDEX_TIMER_A, HRTIM_TIM_IT_REP);
        // __HAL_HRTIM_TIMER_CLEAR_IT(&hhrtim1, HRTIM_TIMERINDEX_TIMER_A, HRTIM_TIM_IT_UPD);
        // __HAL_HRTIM_TIMER_ENABLE_IT(&hhrtim1, HRTIM_TIMERINDEX_TIMER_A, HRTIM_TIM_IT_UPD);
    }
}

static bool fetch_and_reset_adcs(std::optional<Iph_ABC_t>* current0) {
    bool all_adcs_done = (ADC2->ISR & ADC_ISR_EOC)
        && (ADC3->ISR & ADC_ISR_EOC) && (ADC4->ISR & ADC_ISR_EOC);
    if (!all_adcs_done) {
        return false;
    }

    // FIXME: Get vbus from CAN_B

    // volatile uint32_t adc1_dr = ADC1->DR;
    // volatile uint32_t adc4_dr = ADC4->DR;
    volatile uint32_t adc1_cr = ADC1->CR;
    volatile uint32_t adc1_isr = ADC1->ISR;
    volatile uint32_t adc3_cr = ADC3->CR;
    volatile uint32_t adc3_isr = ADC3->ISR;
    volatile uint32_t adc4_cr = ADC4->CR;
    volatile uint32_t adc4_isr = ADC4->ISR;

    std::optional<float> phA = motors[0].phase_current_from_adcval(ADC4->DR);
    std::optional<float> phB = motors[0].phase_current_from_adcval(ADC3->DR);
    // std::optional<float> phC = motors[0].phase_current_from_adcval(ADC1->DR);
    if (phA.has_value() && phB.has_value()) {
        *current0 = {*phA, *phB, -*phA - *phB};
    }

    // Clear ADC flags
    // ADC1->ISR = ~(ADC_ISR_EOC | ADC_ISR_OVR);
    ADC2->ISR = ~(ADC_ISR_EOC | ADC_ISR_OVR);
    ADC3->ISR = ~(ADC_ISR_EOC | ADC_ISR_OVR);
    ADC4->ISR = ~(ADC_ISR_EOC | ADC_ISR_OVR);

    return true;
}

extern "C" {
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart == &huart2) {
        uart2.on_complete();
    }
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart == &huart2) {
        uart2.on_complete();
    }
}

void HAL_HRTIM_RegistersUpdateCallback(HRTIM_HandleTypeDef *hhrtim, uint32_t TimerIdx) {
    if (TimerIdx == HRTIM_TIMERINDEX_TIMER_D) {
        volatile uint32_t timerA_cnt = hhrtim->Instance->sTimerxRegs[HRTIM_TIMERINDEX_TIMER_A].CNTxR;
        volatile uint32_t timerA_rep = hhrtim->Instance->sTimerxRegs[HRTIM_TIMERINDEX_TIMER_A].REPxR;
        volatile bool counting_down = hhrtim->Instance->sTimerxRegs[HRTIM_TIMERINDEX_TIMER_A].CPT1xR & HRTIM_CPT1R_DIR;
        COUNT_IRQ(HRTIM1_TIMD_IRQn);
    }
}

volatile uint32_t timestamp_ = 0;
volatile bool counting_down_ = false;

void HAL_HRTIM_RepetitionEventCallback(HRTIM_HandleTypeDef *hhrtim, uint32_t TimerIdx) {
    if (TimerIdx == HRTIM_TIMERINDEX_TIMER_D) {
        // HAL_ADC_Start_DMA(&hadc1, adc_vals, ADC_CHANNEL_COUNT); // Restart ADC DMA for next round

        volatile uint32_t timerA_cnt = hhrtim->Instance->sTimerxRegs[HRTIM_TIMERINDEX_TIMER_A].CNTxR;
        volatile uint32_t timerA_rep = hhrtim->Instance->sTimerxRegs[HRTIM_TIMERINDEX_TIMER_A].REPxR;
        volatile uint32_t timerA_output_level = HAL_HRTIM_WaveformGetOutputLevel(hhrtim, HRTIM_TIMERINDEX_TIMER_A, HRTIM_OUTPUT_TA1);
        volatile uint32_t timerA_compare1 = hhrtim->Instance->sTimerxRegs[HRTIM_TIMERINDEX_TIMER_A].CMP1xR;
        volatile uint32_t adc_crc = ADC1->CR;

        COUNT_IRQ(HRTIM1_TIMD_IRQn);

        __HAL_HRTIM_TIMER_CLEAR_IT(hhrtim, HRTIM_TIMERINDEX_TIMER_A, HRTIM_TIM_IT_REP);

        // TODO: As ZFOC v1.1 use in-circuit current sampling, we can sample at any time.
        // If the corresponding timer is counting up, we just sampled in SVM vector 0, i.e. real current
        // If we are counting down, we just sampled in SVM vector 7, with zero current
        // bool counting_down = hhrtim->Instance->sTimerxRegs[HRTIM_TIMERINDEX_TIMER_A].CPT1xR & HRTIM_CPT1R_DIR;
        bool counting_down = (timerA_cnt > (HRTIM_PERIOD_CLOCKS));
    
        bool timer_update_missed = (counting_down_ == counting_down);
        if (timer_update_missed) {
            motors[0].disarm_with_error(Motor::ERROR_TIMER_UPDATE_MISSED);
            return;
        }

        counting_down_ = counting_down;
        timestamp_ += HRTIM_PERIOD_CLOCKS * (HRTIM_REP + 1);

        if (!counting_down) {
            TaskTimer::enabled = zfoc.task_timers_armed_;
            // Run sampling handlers and kick off control tasks when TIM8 is
            // counting up.
            zfoc.sampling_cb();
            NVIC->STIR = ControlLoop_IRQn;
        } else {
            // Tentatively reset all PWM outputs to 50% duty cycles. If the control
            // loop handler finishes in time then these values will be overridden
            // before they go into effect.
            motors[0].timer_->Instance->sTimerxRegs[0].CMP1xR =
            motors[0].timer_->Instance->sTimerxRegs[1].CMP1xR =
            motors[0].timer_->Instance->sTimerxRegs[2].CMP1xR =
                HRTIM_PERIOD_CLOCKS / 2;
        }    
    }
}

void ControlLoop_IRQHandler(void) {
    COUNT_IRQ(ControlLoop_IRQn);
    uint32_t timestamp = timestamp_;

    // Ensure that all the ADCs are done
    std::optional<Iph_ABC_t> current0;

    if (!fetch_and_reset_adcs(&current0)) {
        motors[0].disarm_with_error(Motor::ERROR_BAD_TIMING);
    }

    motors[0].current_meas_cb(timestamp, current0);

    zfoc.control_loop_cb(timestamp);

    // By this time the ADCs for both M0 and M1 should have fired again. But
    // let's wait for them just to be sure. 
    // Wait for timer update event to ensure the correct timing. 
    MEASURE_TIME(zfoc.task_times_.dc_calib_wait) {
        // while (!(ADC1->ISR & ADC_ISR_EOC) || !counting_down_);
        while (!counting_down_); // counting_down_ is set in timer update IRQ
        while (!(ADC3->ISR & ADC_ISR_EOC));
    }

    if (!fetch_and_reset_adcs(&current0)) {
        motors[0].disarm_with_error(Motor::ERROR_BAD_TIMING);
    }

    motors[0].dc_calib_cb(timestamp + HRTIM_PERIOD_CLOCKS * (HRTIM_REP + 1), current0);

    motors[0].pwm_update_cb(timestamp + 3 * (HRTIM_PERIOD_CLOCKS * (HRTIM_REP + 1)));

    // If we did everything right, the Timer A repetition handler should have been
    // called exactly once between the start of this function and now.

    if (timestamp_ != timestamp + HRTIM_PERIOD_CLOCKS * (HRTIM_REP + 1)) {
        motors[0].disarm_with_error(Motor::Error::ERROR_CONTROL_DEADLINE_MISSED);
    }

    // Ensure that tasktimer is enabled only once.
    zfoc.task_timers_armed_ = zfoc.task_timers_armed_ && !TaskTimer::enabled;
    TaskTimer::enabled = false;
}

} // extern "C"

